version: '3.4'

networks:
    demodddapp:

services:
  ddddb:
    container_name: ddddb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Q2w3e4r
      - MSSQL_SA_PASSWORD=1Q2w3e4r      
      - MSSQL_PID=Express
    networks:
       - demodddapp
    volumes:  
      - sqlserver_data:/var/opt/mssql  
  ddd.services:
    container_name: ddd-example-with-docker
    image: ${DOCKER_REGISTRY-}dddservices
    build:
      context: .
      dockerfile: DDD/Dockerfile
    ports:
      - 8080:80
      - 56555:443    
    depends_on:
      - ddddb
    environment:
      - DB_HOST=ddddb
      - DB_NAME=DDD 
      - DB_SA_USER_ID=sa
      - DB_SA_PASSWORD=1Q2w3e4r
      - DB_PORT=1433
    networks:
      - demodddapp
volumes:
  sqlserver_data: 
  